### ISSUE TITLE
Wondering How to Select An Victim Label in  train_backdoor_sem.py

### ISSUE THREAD

**Issue by LeonardoLuQAQ** [sunbing7/SODA#1]
Dear SunBing7,
    I hope this finds you well.
    I have a question regarding the selection of the victim class for backdoor attacks.[e.g. in CIFAR10, Target Class:6(Frog) with Vitim Class:1(GreenCars)]

    Could you kindly provide guidance on how to choose or specify the victim class as the target for the backdoor attack within the script?
    Thank you very much f for sharing your work with the community. I look forward to your response.

Best regards,
Leo Lu

**Comment by sunbing7** [comment]
Hi, you can set via argument '--poison_target'

**Comment by sunbing7** [comment]
Hi LeonardolLu, this repo is no longer maintained. Please consider using https://gitlab.com/sunbing7/SODA instead. Thanks.
